CREATE TABLE IF NOT EXISTS bitcoin_market (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    price DOUBLE PRECISION,
    market_cap DOUBLE PRECISION,
    volume DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);